servingEngineSpec:
  runtimeClassName: "crun"

  modelSpec:
    - name: "qwen3"
      repository: "vllm/vllm-openai"
      tag: "v0.8.4"
      modelURL: "/models/Qwen2.5-7B"
      imagePullPolicy: "IfNotPresent" # or "Always"

      replicaCount: 1

      requestCPU: 6
      requestMemory: "8Gi"
      requestGPU: 2

      env:
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: "expandable_segments:True"
      
      
      shmSize: "10Gi"
      vllmConfig:
        #tensorParallelSize: 1
        #pipelineParallelSize: 2
        gpuMemoryUtilization: 0.99
        maxModelLen: 4096
        extraArgs:
          # - "--kv-cache-dtype=fp16"
          - "--dtype"
          - "float16"
          - "--disable-custom-all-reduce"
          - "--enforce-eager"
          - "--trust-remote-code"
          - "--pipeline-parallel-size" 
          - "1"
          - "--tensor-parallel-size" 
          - "2"
      # lmcacheConfig:
      #   enabled: False

      # # (optional) pin to your GPU nodes; label them first
      # #   kubectl label node <node1> gpu=true
      # #   kubectl label node <node2> gpu=true
      # nodeSelector:
      #   gpu: "true"

      extraVolumes:
        - name: local-models
          hostPath:
            path: /models/Qwen2.5-7B   # path on each node
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "10Gi"
      extraVolumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: local-models
          mountPath: /models/Qwen2.5-7B
          readOnly: true




      # Keep replicas on different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  # Adjust if your chart uses different labels; these are common defaults
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["vllm-stack"]
                  - key: app.kubernetes.io/component
                    operator: In
                    values: ["serving-engine"]
              topologyKey: kubernetes.io/hostname

      # Extra safety to spread by node
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["vllm-stack"]
              - key: app.kubernetes.io/component
                operator: In
                values: ["serving-engine"]
 
